// test {
//   assert_eq!(@Binary_Exponentiation.bin_pow(2, 3), 8)
//   assert_eq!(@Binary_Exponentiation.bin_pow(2, 1), 2)
//   assert_eq!(@Binary_Exponentiation.bin_pow(2, 0), 1)
//   assert_eq!(@Binary_Exponentiation.bin_pow(15, 20), 4664335276710460609)
//   assert_eq!(@Binary_Exponentiation.bin_pow_mod(15, 20, 1000000007), 393128630)
//   assert_eq!(@Binary_Exponentiation.bin_pow_mod(2, 3, 3), 2)
// }