name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        version: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Moon
        uses: illusory0x0/setup-moonbit@v0.1.0
        with: 
          version: ${{ matrix.version }} 

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: moon check
        run: moon check --deny-warn

      - name: moon test
        run: |
          moon test
          moon test --target js

      - name: format diff
        run: |
          moon fmt
          git diff --exit-code
